### ISSUE TITLE
Reciprocity 

### ISSUE THREAD

**Issue by shockey** [zfisch/orgy#11]
Currently, people in a given organization who don't run Peeps are able to benefit from people who do, in the form of a higher follower count.

The result of this is a net-negative for people who do decide to run the script- those people end up with a lower follower:following ratio than those that just sit back and reap the benefits.

(CC: @prakal)

**Comment by prakal** [comment]
Totally agree with this issue. Upon conversations with some engineers, I noticed that people who _already_ gained followers due to others running the script were _more_ reticent to run the script. They were quite open about their reason: They had already gained a high follower to following ratio, and did not want to damage it. Some people who have run the script voiced their concerns that running the script doesn't really benefit them.

I believe that Peeps is an automated script to follow members of the community. If some members opt out of it, there is no issue whatsoever. However, as it stands right now, Peeps is an opt-out when it comes to gaining new followers. One way to address this is to make it opt-in, and only select members of the group that are interested in following your work.

**Comment by zfisch** [comment]
Hi @kyleshockey @prakal -- thanks for your feedback.

I would encourage anybody to use or not use the script as they see fit. Also, feel free to fork the repo and reconstruct it however you'd like if you feel you have some ideas for changes (according to the license, of course), or overhaul it altogether!

The purpose of this script as of right now is simply to follow other people in an organization, and since it is currently meeting its goal without error, I am closing this issue. If you notice a bug with the functionality of the program, please let me know and I will do my best to address it.
